include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'
stages:
  - lint
  - build
  - deploy

i18n:
  stage: lint
  script:
    - ./build-aux/test/i18n-strings-check.sh

lint:
  stage: lint
  image: "valalang/lint:latest"
  script:
    - io.elementary.vala-lint src -c build-aux/test/vala-lint.conf

alpine:
  stage: build
  allow_failure: true
  before_script:
    - apk upgrade -a
    - apk add alpine-sdk meson vala gtk4.0-dev libgtop-dev
              libadwaita-dev libgee-dev tracker-dev

  image: alpine:latest
  script:
  - meson setup _build
  - meson compile -C _build

flatpak:
  stage: build
  extends: '.flatpak'
  variables:
    MANIFEST_PATH: 'org.gnome.Usage.json'
    RUNTIME_REPO: 'https://nightly.gnome.org/gnome-nightly.flatpakrepo'
    FLATPAK_MODULE: 'gnome-usage'
    BUNDLE: "org.gnome.UsageDevel.flatpak"
    APP_ID: 'org.gnome.UsageDevel'

nightly:
  stage: deploy
  extends: '.publish_nightly'
  dependencies: ['flatpak']
  needs: ['flatpak']
