include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'
stages:
  - lint
  - build
  - deploy

i18n:
  stage: lint
  script:
    - ./build-aux/test/i18n-strings-check.sh

lint:
  stage: lint
  image: "valalang/lint:latest"
  script:
    - io.elementary.vala-lint src -c build-aux/test/vala-lint.conf

fedora:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - dnf update -y
    - dnf install -y gcc meson gettext gtk-doc vala gtk4-devel libgtop2-devel
                     libadwaita-devel libgee-devel desktop-file-utils
                     redhat-rpm-config tracker-devel

  image: fedora:rawhide
  script:
  - meson _build .
  - ninja -C _build
  - ninja -C _build install

flatpak:
  stage: build
  extends: '.flatpak'
  variables:
    MANIFEST_PATH: 'org.gnome.Usage.json'
    RUNTIME_REPO: 'https://nightly.gnome.org/gnome-nightly.flatpakrepo'
    FLATPAK_MODULE: 'gnome-usage'
    BUNDLE: "org.gnome.UsageDevel.flatpak"
    APP_ID: 'org.gnome.UsageDevel'

nightly:
  stage: deploy
  extends: '.publish_nightly'
  dependencies: ['flatpak']
  needs: ['flatpak']
