include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'
stages:
  - build
  - test
  - deploy

variables:
  BUNDLE: "org.gnome.Usage.Devel.flatpak"

build:
  before_script:
    - dnf update -y
    - dnf install -y gcc meson gettext gtk-doc vala gtk3-devel libgtop2-devel 
                     desktop-file-utils libdazzle-devel tracker-devel
  image: fedora:29
  stage: build
  script:
  - meson _build .
  - ninja -C _build
  - ninja -C _build install

flatpak:
  extends: '.flatpak'
  variables:
    MANIFEST_PATH: 'org.gnome.Usage.json'
    RUNTIME_REPO: 'https://nightly.gnome.org/gnome-nightly.flatpakrepo'
    FLATPAK_MODULE: 'gnome-usage'
    APP_ID: 'org.gnome.UsageDevel'
    MESON_ARGS: '-Dprofile=development'

review:
  dependencies:
    - 'flatpak'
  extends: '.review'

stop_review:
  extends: '.stop_review'

nightly:
  extends: '.publish_nightly'
