image: fedora:28
stages:
  - build
before_script:
  - dnf update -y
  - dnf install -y gcc meson gettext gtk-doc vala gtk3-devel libgtop2-devel
                   desktop-file-utils libdazzle
build-gnome-usage:
  stage: build
  script:
  - meson _build .
  - ninja -C _build
  - ninja -C _build install
