image: fedora:28
stages:
  - build
  - test
  - review
before_script:
  - dnf update -y
  - dnf install -y gcc meson gettext gtk-doc vala gtk3-devel libgtop2-devel
                   desktop-file-utils
build-gnome-usage:
  stage: build
  script:
  - meson _build .
  - ninja -C _build
  - ninja -C _build install

variables:
    BUNDLE: "gnome-usage.flatpak"

flatpak:
    image: registry.gitlab.gnome.org/gnome/gnome-nightly-oci/nightly:master
    stage: test

    variables:
        MANIFEST_PATH: "org.gnome.Usage.json"
        RUNTIME_REPO: "https://sdk.gnome.org/gnome-nightly.flatpakrepo"
        FLATPAK_MODULE: "gnome-usage"
        MESON_ARGS: "-Dtests=all"

    script:
        - flatpak-builder --stop-at=${FLATPAK_MODULE} app ${MANIFEST_PATH}
        - flatpak build app meson --prefix=/app ${MESON_ARGS} _build
        - flatpak build app ninja -C _build install
        - xvfb-run -a -s "-screen 0 1024x768x24" flatpak build app ninja -C _build test
        - flatpak-builder --finish-only --repo=repo app ${MANIFEST_PATH}
        - flatpak build-bundle repo ${BUNDLE} --runtime-repo=${RUNTIME_REPO} org.gnome.Usage
    artifacts:
        paths:
            - ${BUNDLE}
            - _build/meson-logs/meson-log.txt
            - _build/meson-logs/testlog.txt
        expire_in: 30 days
    cache:
        paths:
             - .flatpak-builder/cache

review:
    stage: review
    dependencies:
        - flatpak
    script:
        - echo "Generating flatpak deployment"
    artifacts:
        paths:
            - ${BUNDLE}
        expire_in: 30 days
    environment:
        name: review/$CI_COMMIT_REF_NAME
        url: https://gitlab.gnome.org/$CI_PROJECT_PATH/-/jobs/$CI_JOB_ID/artifacts/raw/${BUNDLE}
        on_stop: stop_review

stop_review:
    stage: review
    script:
        - echo "Stopping flatpak deployment"
    when: manual
    environment:
        name: review/$CI_COMMIT_REF_NAME
        action: stop