include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'
stages:
  - build
  - test
  - deploy

build:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - dnf update -y
    - dnf install -y gcc meson gettext gtk-doc vala gtk3-devel libgtop2-devel libhandy-devel
                     desktop-file-utils libdazzle-devel redhat-rpm-config
    - dnf install -y dnf-plugins-core && dnf copr enable -y ssssam/tracker3 && dnf install --nogpg -y tracker3-devel

  image: fedora:34
  stage: build
  script:
  - meson _build .
  - ninja -C _build
  - ninja -C _build install

flatpak:
  extends: '.flatpak'
  variables:
    MANIFEST_PATH: 'org.gnome.Usage.json'
    RUNTIME_REPO: 'https://nightly.gnome.org/gnome-nightly.flatpakrepo'
    FLATPAK_MODULE: 'gnome-usage'
    BUNDLE: "org.gnome.Usage.Devel.flatpak"
    APP_ID: 'org.gnome.UsageDevel'

nightly:
  extends: '.publish_nightly'
  dependencies: ['flatpak']
  needs: ['flatpak']
