include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'
stages:
  - test
  - deploy

fedora:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - dnf5 update -y
    - dnf5 install -y gcc meson gettext gtk-doc vala gtk4-devel libgtop2-devel
                      libadwaita-devel libgee-devel desktop-file-utils
                      redhat-rpm-config tracker-devel

  image: fedora:rawhide
  stage: test
  script:
  - meson _build .
  - ninja -C _build
  - ninja -C _build install

flatpak:
  extends: '.flatpak'
  variables:
    MANIFEST_PATH: 'org.gnome.Usage.json'
    RUNTIME_REPO: 'https://nightly.gnome.org/gnome-nightly.flatpakrepo'
    FLATPAK_MODULE: 'gnome-usage'
    BUNDLE: "org.gnome.UsageDevel.flatpak"
    APP_ID: 'org.gnome.UsageDevel'

nightly:
  extends: '.publish_nightly'
  dependencies: ['flatpak']
  needs: ['flatpak']
