vala_sources = [
  'application.vala',
  'settings.vala',
  'utils.vala',
  'monitor/app-item.vala',
  'monitor/background-monitor.vala',
  'monitor/cpu-monitor.vala',
  'monitor/gamemode-monitor.vala',
  'monitor/memory-monitor.vala',
  'monitor/monitor.vala',
  'monitor/process.vala',
  'monitor/query-builder.vala',
  'monitor/sparql-controller.vala',
  'monitor/sparql-worker.vala',
  'monitor/system-monitor.vala',
  'monitor/vnstat.vala',
  'ui/graph.vala',
  'ui/graph-box.vala',
  'ui/speedometer.vala',
  'ui/stack-list.vala',
  'ui/view.vala',
  'ui/window.vala',
  'ui/network/network-interface-graph.vala',
  'ui/network/network-view.vala',
  'ui/performance/app-dialog.vala',
  'ui/performance/cpu-graph.vala',
  'ui/performance/cpu-view.vala',
  'ui/performance/memory-graph.vala',
  'ui/performance/memory-speedometer.vala',
  'ui/performance/memory-view.vala',
  'ui/performance/no-results-found-view.vala',
  'ui/performance/performance-graph-view.vala',
  'ui/performance/process-list-box.vala',
  'ui/performance/process-row-item.vala',
  'ui/performance/process-user-tag.vala',
  'ui/performance/quit-process-dialog.vala',
  'ui/performance/swap-speedometer.vala',
  'ui/storage/storage-actionbar.vala',
  'ui/storage/storage-graph.vala',
  'ui/storage/storage-view.vala',
  'ui/storage/storage-view-item.vala',
  'ui/storage/storage-view-row.vala',
]

deps = [
  gee_dep,
  gio_dep,
  gio_unix_dep,
  glib_dep,
  gobject_dep,
  gtk_dep,
  json_dep,
  libgtop_dep,
  libnm_dep,
  tinysparql_dep,
  libadwaita_dep,
  cc.find_library('m'),
  valac.find_library('config', dirs: src_dir),
  valac.find_library('stopgap', dirs: vapi_dir),
  valac.find_library('posix')
]

c_args = [
  '-DVERSION="@0@@1@"'.format(meson.project_version(), version_suffix),
  '-DGETTEXT_PACKAGE="@0@"'.format(meson.project_name()),
  '-DGNOMELOCALEDIR="@0@"'.format(join_paths(get_option('prefix'), get_option('localedir'))),
  '-DPROFILE="@0@"'.format(profile),
  '-DAPPLICATION_ID="@0@"'.format(application_id),
  '-DAPPLICATION_RESOURCE_PATH="@0@"'.format(resource_path),
  '-DG_LOG_DOMAIN="@0@"'.format(meson.project_name()),
]

executable(
  meson.project_name(),
  vala_sources + resources,
  dependencies: deps,
  c_args: c_args,
  vala_args: vapi_dirs,
  install: true
)
